### ISSUE TITLE
[GCI] Feature Request | Methods of Portal Creation & Variety of Portals

### ISSUE THREAD

**Issue by smsunarto** [Terasology/Portals#2]
# Methods of Portal Creation & Variety of Portals

## Overview
If you want to create a Portal now, you need to get the portal block or use the give command. I believe  we can improve the overall gameplay if there's a method to create portals manually. Each portals will have a different method of creation. 

There will be 2 types of portal, portals that spawns aggressive monsters that attacks player, and portals that spawns sentinel that can help guard the player/city/structure that will spawn another sentinel if the previous sentinel dies and there's still some materials in the inventory of the portal to create another sentinel.

Some portal will be harder than other to make depending on the usefulness of that particular portal.

**What should be added to make this feature functional:**
- Blocks that can be used to spawn specific portal. (Ex: Portal Frame)
- Item that can trigger a monument to create a portal.
- Monument formation shapes file.
- Sentinels monster that can be spawn through portals.
- Portal inventory.

## System
The system for the portal creation will be pretty straight-forward.

1. The player builds a monument/structure to spawn the portal. (The monument/structure varies between portals).
2. The player uses an item/offering to trigger the monument to create a portal.
3. The portal is created and the portal will automatically start spawning monsters/animals.

## Affect to player & gameplay
With this new added feature, it would allow players to be more creative with using portals. We could add some monster that drops rare/useful item when killed, so that the player would be incentivize the player to create that particular portal.

 We could also create a portal that spawns sentinels(s) that can help the player defend their house/cities/town from attacking mobs/players. This sentinel will be created using items in the portal's inventory, if there's enough materials the sentinel will be spawned after the previous one is killed. This will improve the overall base building strategies for player. They will try to optimize the portal location so that their sentinel can always protect their base.

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
